### ISSUE TITLE
Feature: User can generate a New Game, List, Word

### ISSUE THREAD

**Issue by brij8** [brij8/wordlist#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a New Game, New List, and New Word
-click 'new' generates blank 'New Game/List/Word' object

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can click 'Games' or 'Lists' to move to respective page.
In Games/Lists, can click 'New' and a New Game/List/Word will be generated named 'New Game/List/Word'.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![wl-games01](https://user-images.githubusercontent.com/42279790/163488555-7f9f305c-5a8e-4056-a666-e5bd7ff2b55f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` with queries to add Game to correct table.
- [ ] Update `server/index.js` with queries to add List to correct table.
- [ ] Update `server/index.js` with queries to add Word to correct table.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] comments explaining all functions/features
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
