### ISSUE TITLE
Refactor: All dom.querySelectors into Reacts Refs

### ISSUE THREAD

**Issue by brij8** [brij8/wordlist#19]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

Find all instances of DOM manip/querySelection and refactor into React Refs wherever possible. 
Should only be in a handful of places, mostly to grab input fields/values.

- [ ] ... 
- [x] --- LISTS.jsx:
- [x] 134 .querySelector('.modal');
- [x] 136 .querySelector('#editInput');
- [x] 147 .querySelector('#editInput').value;
- [x] 178 .querySelector('.modal');
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
