### ISSUE TITLE
Feature: User can edit Words

### ISSUE THREAD

**Issue by brij8** [brij8/wordlist#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit Words.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a blank New Word has been generated, user can select that word and then:
Either double-click the word, or click Edit.
Modal appears and allows user to change the text of that word.
Press enter, or click save changes to commit changes.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] dbl-click/edit btn opens modal
- [ ] modal input field auto-focuses
- [ ] modal input field is clear of previous used text
- [ ] close & X btns remove modal
- [ ] save changes btn & enter press send changes to tables
- [ ] changes display immediately

### ☁️ Server

- [ ] Update `server/index.js` to update correct data on correct table and send updated response for display.
- [ ] catch json response and feed it to function that refreshes displayed words.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] comments explaining all functions/features
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
