### ISSUE TITLE
Feature: User can edit Game names

### ISSUE THREAD

**Issue by brij8** [brij8/wordlist#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the name of selected Game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a blank New Game has been generated, user can select that game and then:
Either double-click the game, or click Edit.
Modal appears and allows user to change the text of that game.
Press enter, or click save changes to commit changes.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] dbl-click/edit btn opens modal
- [x] modal input field auto-focuses
- [x] modal input field is clear of previous used text
- [x] close & X btns remove modal
- [x] save changes btn & enter press send changes to tables
- [x] changes display immediately

### ☁️ Server

- [x] Update `server/index.js` to update correct data on correct table and send updated response for display.
- [x] catch json response and feed it to function that refreshes displayed games.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] comments explaining all functions/features
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
